repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        # language_version: python3.11
        args: [--line-length, "79"]
        files: ^src/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        # name: mypy
        # entry: mypy
        # language_version: python3.11
        # args: [--strict-optional, --ignore-missing-imports, .]
        files: ^src/

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^src/
