repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
        args: [--line-length, 79]
        files: ^src/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language_version: python3.8
        args: [--strict-optional, --ignore-missing-imports, .]
        files: ^src/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language_version: python3.8
        args: [--config, .flake8, .]
        files: ^src/
